# Generated by Django 5.0.2 on 2024-02-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilaus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_numero',
            field=models.CharField(max_length=6),
        ),
    ]
