# Generated by Django 5.0.2 on 2024-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilaus', '0002_alter_product_name_alter_product_s_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kuva',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='s_numero',
            field=models.CharField(max_length=7),
        ),
    ]
