# Generated by Django 5.0.2 on 2024-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilaus', '0005_toimittaja_tuotesarja_product_toimittajan_tuotekoodi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='toimittaja',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tuotesarja',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
